Update terragrunt-repo-creation-backstage.yaml

diff --git a/.github/workflows/terragrunt-repo-creation-backstage.yaml b/.github/workflows/terragrunt-repo-creation-backstage.yaml
--- a/.github/workflows/terragrunt-repo-creation-backstage.yaml
+++ b/.github/workflows/terragrunt-repo-creation-backstage.yaml
@@ -27,7 +27,7 @@ jobs:
       - name: Echo Message
         run: echo "${{ inputs.message }}"
 
-      - name: Force failure (test)
-        run: |
-          echo "Forcing workflow failure for test"
-          exit 1
+      # - name: Force failure (test)
+      #   run: |
+      #     echo "Forcing workflow failure for test"
+      #     exit 1
